### PR TITLE
Add gradle build and lint action

### PR DESCRIPTION
**Pull request by yavko**

### CODE REVIEW

**Comment by yavko** [comment]
Sorry for all the commits ;(

**Comment by yavko** [comment]
it seems @LFC6times doesn't want it, ill just close it for now, (wow we both closed at same time)

**Comment by ebay-kid** [comment]
I don't really think this is necessary for our use case, since the extent of this is checking for compilation issues that the IDE can also catch.

**Comment by yavko** [comment]
> I don't really think this is necessary for our use case, since the extent of this is checking for compilation issues that the IDE can also catch.

I thought it would be useful for PR reviewers

**Pull request closed without merging**
